---
apiVersion: v1
kind: Service
metadata:
  name: weather-store
  labels:
    app: weather
spec:
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-store
  labels:
    app: weather
spec:
  selector:
    matchLabels:
      app: weather-store
  replicas: 1
  template:
    metadata:
      labels:
        app: weather-store
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - image: 418330922897.dkr.ecr.ap-northeast-1.amazonaws.com/weather-store
          name: weather-store
          env:
            - name: DB_HOST
              value: "postgresql"
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: <username>
            - name: DB_PASSWORD
              value: <password>
            - name: DB_NAME
              value: <dbname>
          ports:
            - containerPort: 8080
              name: weather-store
